version: '3'
services:
  #Apache
  # apache_server:
  #   container_name: alpha_apache
  #   build: ./apache_server
  #   volumes:
  #     - ../alpha:/var/www/project
  #   ports:
  #     - "8001:80"
  #   tty: true
  #Nginx
  behat_nginx:
    container_name: behat_nginx
    build: ./nginx_server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../behat:/var/www/project
    ports:
      - "8000:80"
    tty: true
  #MYSQL
  behat_mysql:
    container_name: behat_mysql
    build: ./mysql
    tty: true
    ports:
      - "43306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root@secret123
  #REDIS
  # project_redis:
  #   container_name: project_redis
  #   build: ./redis
  #   ports:
  #       - "6379:6379"
  #RabbitMQ
  # project_rabbit:
  #   container_name: project_rabbit
  #   image: rabbitmq
  #   ports:
  #       - "5672:5672"
  #       - "15672:15672"
  #RabbitMQ_Management (username/passwd: guest/guest)
  # rabbit_admin:
  #   image: rabbitmq:management
  #   container_name: rabbit_admin
  #   ports:
  #     - "8080:15672"
networks:
  default:
    name: laravel5.4-behat-network

